version: '3.8'

services:
  backend:
    build: ./backend
    container_name: smartphone-manager-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: smartphone-manager-frontend
    ports:
      - "90:90"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network

networks:
  app-network:
    driver: bridge