version: '3.8'

services:
  backend:
    build: ./backend
    container_name: smartphone-manager-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/smartphone-manager
      - IMEI_API_KEY=${IMEI_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: smartphone-manager-frontend
    ports:
      - "90:90"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge